{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-capushe
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/capushe_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/capushe/capushe_{{ version }}.tar.gz
  sha256: 6cf159ae06fc3a00a503c4300f35d5df87c3fc57c0e4767e84c7dc19723447a9

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('capushe')"           # [not win]
    - "\"%R%\" -e \"library('capushe')\""  # [win]

about:
  home: http://www.math.u-psud.fr/~brault/capushe.html
  license: GPL-2.0-or-later
  summary: Calibration of penalized criteria for model selection. The calibration methods available
    are based on the slope heuristics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
