travis:
  secure:
    BINSTAR_TOKEN: PQaX/6sjyNPR2AR/sxRUS++ZCdkPptYpFk9ccuKwij59trfN9He9Z+CHR8WCq7gio+SGRmlIf3HZ6n92TGO0StqhJMvU//ne+pv1oviw38/ZDHPI6MhxiwJmgqWOP+tpebtYCBC4LikZ6s9uBgS3Sk4UEL3e5FbP/VQz4V0OxhqV7p8A5W7TkTq9lQrXnYdJ5l4Q6xncg/CW++H4pEHgBvEpqv1gpUvVdmi87/CNOo1mv2HpsaCv+bRshb0TSaK6FFytg/kkAiXeH6LJz+a3MalnNSkohj4gKkQj89CyOpFnZkmLNsONqSS61XSjLR3MADQM3AEwcSbopFmhadg0cIPrkn6wK0SgoZmUyjcF7VRC/z7cMpsx47RflhUvS4Ului1oW91Ua8eR2BCDSf/lyXwqVy05fcc9IICnYL0TrMGv1cBX3wgy7GpHfqBXgWnvnaMhVDLf1NsUy081RtPrTD6lwFEy6fHC2YWDGvuv7fRkhVdaW4uo0w8eUkkJdswiqk6eUdM6apaiNN3mkQYEgQ45ak7HYoWqsiePl7VUYIhrhGXC+/XqYzYGkHTKQqdEpPIhPMozft/vT+XMbEbC2lsN71MutrS1RWnRjEswkH49ILzX34/TZYdZTsGwHvkcsQi3aWWh4NeTMtH5N/5550g0mcTQQMFN8JA1VIi5aIg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
